export interface Movie {
  id: string;
  title: string;
  year: number;
  genres: string[];
  runtime: number; // in minutes
  rating: number; // e.g. 8.8
  language: string;
  mood: string;
  poster: string;
  trailer: string; // YouTube embed ID (e.g. "dQw4w9WgXcQ" or full URL)
  overview: string;
}

export const MOCK_MOVIES: Movie[] = [
  {
    id: "m1",
    title: "Interstellar",
    year: 2014,
    genres: ["Sci-Fi", "Adventure", "Drama"],
    runtime: 169,
    rating: 8.7,
    language: "English",
    mood: "Mind-Bending",
    poster: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&auto=format&fit=crop&q=60",
    trailer: "zSWdZVtXT7E",
    overview: "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage."
  },
  {
    id: "m2",
    title: "Inception",
    year: 2010,
    genres: ["Action", "Sci-Fi", "Adventure"],
    runtime: 148,
    rating: 8.8,
    language: "English",
    mood: "Mind-Bending",
    poster: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&auto=format&fit=crop&q=60",
    trailer: "YoHD9XEInc0",
    overview: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project."
  },
  {
    id: "m3",
    title: "Parasite",
    year: 2019,
    genres: ["Thriller", "Drama", "Comedy"],
    runtime: 132,
    rating: 8.5,
    language: "Korean",
    mood: "Dark",
    poster: "https://images.unsplash.com/photo-1568832359672-e36cf5d74f54?w=500&auto=format&fit=crop&q=60",
    trailer: "5xH0HfJHsaY",
    overview: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan."
  },
  {
    id: "m4",
    title: "Spirited Away",
    year: 2001,
    genres: ["Animation", "Adventure", "Family", "Drama"],
    runtime: 125,
    rating: 8.6,
    language: "Japanese",
    mood: "Feel Good",
    poster: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=500&auto=format&fit=crop&q=60",
    trailer: "ByXuk9QqQMC",
    overview: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts."
  },
  {
    id: "m5",
    title: "The Dark Knight",
    year: 2008,
    genres: ["Action", "Thriller", "Drama"],
    runtime: 152,
    rating: 9.0,
    language: "English",
    mood: "Dark",
    poster: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=500&auto=format&fit=crop&q=60",
    trailer: "LDG9bisJEaI",
    overview: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice."
  },
  {
    id: "m6",
    title: "Superbad",
    year: 2007,
    genres: ["Comedy"],
    runtime: 113,
    rating: 7.6,
    language: "English",
    mood: "Funny",
    poster: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=500&auto=format&fit=crop&q=60",
    trailer: "277_P-L7d-g",
    overview: "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry."
  },
  {
    id: "m7",
    title: "3 Idiots",
    year: 2009,
    genres: ["Comedy", "Drama"],
    runtime: 170,
    rating: 8.4,
    language: "Hindi",
    mood: "Feel Good",
    poster: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=500&auto=format&fit=crop&q=60",
    trailer: "K0eDb37-8RY",
    overview: "Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently, even as the world called them idiots."
  },
  {
    id: "m8",
    title: "Your Name.",
    year: 2016,
    genres: ["Animation", "Romance", "Drama", "Sci-Fi"],
    runtime: 106,
    rating: 8.4,
    language: "Japanese",
    mood: "Emotional",
    poster: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&auto=format&fit=crop&q=60",
    trailer: "hRfHcp2G69c",
    overview: "Two strangers find themselves linked in a bizarre way. When a connection is formed, will distance be the only thing to keep them apart?"
  },
  {
    id: "m9",
    title: "The Hangover",
    year: 2009,
    genres: ["Comedy"],
    runtime: 100,
    rating: 7.7,
    language: "English",
    mood: "Funny",
    poster: "https://images.unsplash.com/photo-1518173946687-a4c8a383392e?w=500&auto=format&fit=crop&q=60",
    trailer: "tcdUyk8fVyI",
    overview: "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They make their way around the city in order to find their friend before his wedding."
  },
  {
    id: "m10",
    title: "Spiderman: Into the Spider-Verse",
    year: 2018,
    genres: ["Animation", "Action", "Adventure", "Sci-Fi"],
    runtime: 117,
    rating: 8.4,
    language: "English",
    mood: "Exciting",
    poster: "https://images.unsplash.com/photo-1635805737707-575885ab0820?w=500&auto=format&fit=crop&q=60",
    trailer: "g4Hbz2jLxLk",
    overview: "Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions to stop a threat for all realities."
  },
  {
    id: "m11",
    title: "Knives Out",
    year: 2019,
    genres: ["Comedy", "Mystery", "Thriller"],
    runtime: 130,
    rating: 7.9,
    language: "English",
    mood: "Exciting",
    poster: "https://images.unsplash.com/photo-1585647347384-2593bc35786b?w=500&auto=format&fit=crop&q=60",
    trailer: "qGqiHJTsRkQ",
    overview: "A detective investigates the death of the patriarch of an eccentric, combative family."
  },
  {
    id: "m12",
    title: "The Conjuring",
    year: 2013,
    genres: ["Horror", "Mystery", "Thriller"],
    runtime: 112,
    rating: 7.5,
    language: "English",
    mood: "Dark",
    poster: "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=500&auto=format&fit=crop&q=60",
    trailer: "k10ETZ42q5o",
    overview: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse."
  },
  {
    id: "m13",
    title: "About Time",
    year: 2013,
    genres: ["Romance", "Drama", "Comedy", "Sci-Fi"],
    runtime: 123,
    rating: 7.8,
    language: "English",
    mood: "Feel Good",
    poster: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=500&auto=format&fit=crop&q=60",
    trailer: "T7A810duHvw",
    overview: "At the age of 21, Tim discovers he can travel in time and change what happens and has happened in his own life. His decision to make his world a better place by getting a girlfriend turns out to be not as easy as you might think."
  },
  {
    id: "m14",
    title: "Whiplash",
    year: 2014,
    genres: ["Drama"],
    runtime: 106,
    rating: 8.5,
    language: "English",
    mood: "Exciting",
    poster: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=500&auto=format&fit=crop&q=60",
    trailer: "7d_jQyG8DjQ",
    overview: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential."
  },
  {
    id: "m15",
    title: "The Matrix",
    year: 1999,
    genres: ["Action", "Sci-Fi"],
    runtime: 136,
    rating: 8.7,
    language: "English",
    mood: "Mind-Bending",
    poster: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=500&auto=format&fit=crop&q=60",
    trailer: "vKQi3bBA1y8",
    overview: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence."
  },
  {
    id: "m16",
    title: "A Silent Voice",
    year: 2016,
    genres: ["Animation", "Drama", "Romance"],
    runtime: 130,
    rating: 8.1,
    language: "Japanese",
    mood: "Emotional",
    poster: "https://images.unsplash.com/photo-1541560052-5e137f229371?w=500&auto=format&fit=crop&q=60",
    trailer: "Y3UXDKJV810",
    overview: "A young man is mutually ostracized by his classmates after he bullies a deaf girl to the point where she moves away. Years later, he sets off on a path for redemption."
  },
  {
    id: "m17",
    title: "Oldboy",
    year: 2003,
    genres: ["Action", "Thriller", "Drama", "Mystery"],
    runtime: 120,
    rating: 8.4,
    language: "Korean",
    mood: "Dark",
    poster: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=500&auto=format&fit=crop&q=60",
    trailer: "tN7WigB8o4Q",
    overview: "After being kidnapped and imprisoned for fifteen years, Oh Dae-Su is released, only to find that he must find his captor in five days."
  },
  {
    id: "m18",
    title: "Dangal",
    year: 2016,
    genres: ["Action", "Biography", "Drama"],
    runtime: 161,
    rating: 8.3,
    language: "Hindi",
    mood: "Emotional",
    poster: "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=500&auto=format&fit=crop&q=60",
    trailer: "x_7YlGv9u1g",
    overview: "Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression."
  },
  {
    id: "m19",
    title: "Maula Jatt (The Legend of)",
    year: 2022,
    genres: ["Action", "Drama"],
    runtime: 153,
    rating: 8.0,
    language: "Urdu",
    mood: "Exciting",
    poster: "https://images.unsplash.com/photo-1599733589046-9b8308b5b50d?w=500&auto=format&fit=crop&q=60",
    trailer: "pEWqacYzqnI",
    overview: "A fierce prizefighter with a scarred past seeks vengeance against his arch nemesis Noori Natt, the most feared warrior in the land of Punjab."
  },
  {
    id: "m20",
    title: "Get Out",
    year: 2017,
    genres: ["Horror", "Mystery", "Thriller"],
    runtime: 104,
    rating: 7.8,
    language: "English",
    mood: "Dark",
    poster: "https://images.unsplash.com/photo-1533928298208-27ff66555d8d?w=500&auto=format&fit=crop&q=60",
    trailer: "DzfpyUBc3Y4",
    overview: "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception eventually reaches a boiling point."
  },
  {
    id: "m21",
    title: "The Lion King",
    year: 1994,
    genres: ["Animation", "Adventure", "Drama", "Family"],
    runtime: 88,
    rating: 8.5,
    language: "English",
    mood: "Family Friendly",
    poster: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=500&auto=format&fit=crop&q=60",
    trailer: "lFzUTdxA2g4",
    overview: "A young lion prince is cast out of his pride by his cruel uncle, who claims he caused his father's death. While the uncle rules with an iron paw, the prince grows up beyond the Savannah, living by a philosophy: No worries."
  },
  {
    id: "m22",
    title: "La La Land",
    year: 2016,
    genres: ["Romance", "Drama", "Comedy"],
    runtime: 128,
    rating: 8.0,
    language: "English",
    mood: "Emotional",
    poster: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=500&auto=format&fit=crop&q=60",
    trailer: "0pdqf4P9MB8",
    overview: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future."
  },
  {
    id: "m23",
    title: "WALL-E",
    year: 2008,
    genres: ["Animation", "Adventure", "Family", "Sci-Fi"],
    runtime: 98,
    rating: 8.4,
    language: "English",
    mood: "Family Friendly",
    poster: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=60",
    trailer: "CZ1CAT3X214",
    overview: "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind."
  },
  {
    id: "m24",
    title: "Sherlock Holmes",
    year: 2009,
    genres: ["Action", "Adventure", "Mystery", "Comedy"],
    runtime: 128,
    rating: 7.6,
    language: "English",
    mood: "Exciting",
    poster: "https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?w=500&auto=format&fit=crop&q=60",
    trailer: "J7nJbzy9yRE",
    overview: "Detective Sherlock Holmes and his stalwart partner John Watson engage in a battle of wits and brawn with a nemesis whose plot is a threat to all of England."
  },
  {
    id: "m25",
    title: "Pulp Fiction",
    year: 1994,
    genres: ["Thriller", "Drama"],
    runtime: 154,
    rating: 8.9,
    language: "English",
    mood: "Dark",
    poster: "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=500&auto=format&fit=crop&q=60",
    trailer: "s7EdQ4FqbhY",
    overview: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption."
  },
  {
    id: "m26",
    title: "My Neighbor Totoro",
    year: 1988,
    genres: ["Animation", "Family", "Adventure"],
    runtime: 86,
    rating: 8.1,
    language: "Japanese",
    mood: "Family Friendly",
    poster: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=500&auto=format&fit=crop&q=60",
    trailer: "92a7Hj0ijPE",
    overview: "When two young girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby."
  },
  {
    id: "m27",
    title: "Gladiator",
    year: 2000,
    genres: ["Action", "Adventure", "Drama"],
    runtime: 155,
    rating: 8.5,
    language: "English",
    mood: "Exciting",
    poster: "https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=500&auto=format&fit=crop&q=60",
    trailer: "owK1qxDselE",
    overview: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery."
  },
  {
    id: "m28",
    title: "Zootopia",
    year: 2016,
    genres: ["Animation", "Comedy", "Family", "Adventure"],
    runtime: 108,
    rating: 8.0,
    language: "English",
    mood: "Family Friendly",
    poster: "https://images.unsplash.com/photo-1535498730771-e735b998cd64?w=500&auto=format&fit=crop&q=60",
    trailer: "jWM0ct-OLsM",
    overview: "In a city of anthropomorphic animals, a rookie bunny cop and a cynical con artist fox must work together to uncover a conspiracy."
  },
  {
    id: "m29",
    title: "Before Sunrise",
    year: 1995,
    genres: ["Romance", "Drama"],
    runtime: 101,
    rating: 8.1,
    language: "English",
    mood: "Relaxing",
    poster: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=500&auto=format&fit=crop&q=60",
    trailer: "25v7N34R5HE",
    overview: "A young man and woman meet on a train in Europe, and wind up spending one evening together in Vienna. However, both know that this will probably be their only night together."
  },
  {
    id: "m30",
    title: "Chugesh (Joyland)",
    year: 2022,
    genres: ["Drama", "Romance"],
    runtime: 126,
    rating: 7.6,
    language: "Urdu",
    mood: "Emotional",
    poster: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500&auto=format&fit=crop&q=60",
    trailer: "3t-S6L2bKws",
    overview: "As the happily patriarchal Rana family yearns for the birth of a baby boy, their youngest son secretly joins an erotic dance theater and falls for a trans starlet."
  }
];
